### ISSUE TITLE
Modules containing digits in their names are missing

### ISSUE THREAD

**Issue by choroba** [trapd00r/Acme-DependOnEverything#1]

**Comment by choroba** [comment]
For example [Compress::Deflate7](http://p3rl.org/Compress::Deflate7), [XML::XSH2](http://p3rl.org/XML::XSH2), or [Convert::ASN1](http://p3rl.org/Convert::ASN1).

**Comment by trapd00r** [comment]
Thank you, 5647 additional dists added for your pleasure!

**Comment by trapd00r** [comment]
... but with those added dists, I can no longer make dist. 

`Makefile:489: *** Recipe has too many lines (71805d).  Stop.`

**Comment by choroba** [comment]
Maybe some other `make` can handle that? The one from bsd maybe?
